/**
 * The museum articles' sources, set in the house citation style.
 *
 * The curation package records each source as one free-form bibliography line
 * (handoff/museum-upgrade/article-metadata/<slug>.json → sources[]). Splitting
 * those lines by rule gets initials, editions and series numbers wrong, so each
 * one is set here by hand: [kind, creators, title, publisher, year, locator].
 * Only what the line itself states is used; a source whose line gives no year
 * has none. "=<slug>/<id>" marks the same work cited again by another article.
 *
 * Read by tools/import-museum-articles.mjs, which fails on any source missing here.
 */
export const SOURCES = {
  "perceptron/S1": [
    "paper",
    "F. Rosenblatt",
    "The perceptron: A probabilistic model for information storage and organization in the brain",
    "Psychological Review 65(6), 386–408",
    1958,
    "doi:10.1037/h0042519",
  ],
  "perceptron/S2": [
    "web",
    "scikit-learn developers",
    "Perceptron API reference",
    "scikit-learn 1.9.1 documentation",
    null,
    "",
  ],
  "perceptron/S3": [
    "book",
    "M. Minsky, S. Papert",
    "Perceptrons: An Introduction to Computational Geometry",
    "MIT Press, expanded edition",
    1988,
    "original edition 1969",
  ],
  "backpropagation/S1": [
    "paper",
    "D. E. Rumelhart, G. E. Hinton, R. J. Williams",
    "Learning representations by back-propagating errors",
    "Nature 323(6088), 533–536",
    1986,
    "doi:10.1038/323533a0",
  ],
  "backpropagation/S2": [
    "paper",
    "A. G. Baydin, B. A. Pearlmutter, A. A. Radul, J. M. Siskind",
    "Automatic Differentiation in Machine Learning: a Survey",
    "Journal of Machine Learning Research 18(153), 1–43",
    2018,
    "",
  ],
  "backpropagation/S3": ["web", "PyTorch contributors", "Autograd mechanics", "PyTorch documentation", null, ""],
  "backpropagation/S4": [
    "book",
    "I. Goodfellow, Y. Bengio, A. Courville",
    "Deep Learning",
    "MIT Press",
    2016,
    "Chapters 6 and 10",
  ],
  "llm-generation/S1": [
    "paper",
    "T. B. Brown, et al.",
    "Language Models are Few-Shot Learners",
    "Advances in Neural Information Processing Systems 33",
    2020,
    "",
  ],
  "llm-generation/S2": [
    "paper",
    "A. Vaswani, et al.",
    "Attention Is All You Need",
    "Advances in Neural Information Processing Systems 30",
    2017,
    "",
  ],
  "llm-generation/S3": ["web", "Hugging Face", "Tokenization algorithms", "Transformers documentation", null, ""],
  "llm-generation/S4": ["web", "Hugging Face", "Generation strategies", "Transformers documentation", null, ""],
  "llm-generation/S5": [
    "paper",
    "A. Holtzman, J. Buys, L. Du, M. Forbes, Y. Choi",
    "The Curious Case of Neural Text Degeneration",
    "International Conference on Learning Representations (ICLR 2020)",
    2020,
    "arXiv:1904.09751",
  ],
  "llm-generation/S6": [
    "paper",
    "National Institute of Standards and Technology",
    "Artificial Intelligence Risk Management Framework: Generative Artificial Intelligence Profile",
    "",
    2024,
    "NIST AI 600-1",
  ],
  "agent-architecture/S1": [
    "paper",
    "S. Yao, et al.",
    "ReAct: Synergizing Reasoning and Acting in Language Models",
    "",
    2022,
    "arXiv:2210.03629, revised 2023",
  ],
  "agent-architecture/S2": ["web", "Anthropic", "Building effective agents", "Anthropic Engineering", 2024, ""],
  "agent-architecture/S3": ["web", "OpenAI", "Function calling guide", "OpenAI API documentation", null, ""],
  "agent-architecture/S4": [
    "web",
    "OWASP Foundation",
    "LLM01:2025 Prompt Injection",
    "OWASP Gen AI Security Project",
    2025,
    "",
  ],
  "model-serving/S1": [
    "paper",
    "D. Crankshaw, X. Wang, G. Zhou, M. J. Franklin, J. E. Gonzalez, I. Stoica",
    "Clipper: A Low-Latency Online Prediction Serving System",
    "14th USENIX Symposium on Networked Systems Design and Implementation (NSDI 17), 613–627",
    2017,
    "",
  ],
  "model-serving/S2": ["web", "NVIDIA", "Batchers", "NVIDIA Triton Inference Server User Guide", null, ""],
  "model-serving/S3": [
    "web",
    "Amazon Web Services",
    "Deploy models for inference",
    "Amazon SageMaker AI Developer Guide",
    null,
    "",
  ],
  "ai-evaluation/S1": [
    "paper",
    "P. Liang, et al.",
    "Holistic Evaluation of Language Models",
    "",
    2022,
    "arXiv:2211.09110",
  ],
  "ai-evaluation/S2": [
    "paper",
    "National Institute of Standards and Technology",
    "Artificial Intelligence Risk Management Framework (AI RMF 1.0)",
    "",
    2023,
    "NIST AI 100-1, doi:10.6028/NIST.AI.100-1",
  ],
  "ai-evaluation/S3": [
    "paper",
    "L. Zheng, et al.",
    "Judging LLM-as-a-Judge with MT-Bench and Chatbot Arena",
    "",
    2023,
    "arXiv:2306.05685",
  ],
  "ai-assisted-development/S1": [
    "paper",
    "C. E. Jimenez, et al.",
    "SWE-bench: Can Language Models Resolve Real-World GitHub Issues?",
    "",
    2023,
    "arXiv:2310.06770",
  ],
  "ai-assisted-development/S2": [
    "paper",
    "J. Becker, N. Rush, E. Barnes, D. Rein",
    "Measuring the Impact of Early-2025 AI on Experienced Open-Source Developer Productivity",
    "",
    2025,
    "arXiv:2507.09089",
  ],
  "ai-assisted-development/S3": [
    "web",
    "GitHub",
    "Responsible use of GitHub Copilot code completion",
    "GitHub Docs",
    null,
    "",
  ],
  "programming-languages/S1": ["web", "MDN Web Docs", "JavaScript execution model", "", null, ""],
  "programming-languages/S2": ["web", "TypeScript", "Everyday Types: Erased Types", "", null, ""],
  "programming-languages/S3": ["web", "TC39", "ECMAScript Language Specification", "", null, ""],
  "frameworks-libraries/S1": [
    "web",
    "M. Fowler",
    "Inversion of Control Containers and the Dependency Injection pattern",
    "",
    null,
    "",
  ],
  "frameworks-libraries/S2": ["web", "Django Software Foundation", "Django overview", "", null, ""],
  "frameworks-libraries/S3": ["web", "React", "Learn React", "", null, ""],
  "frontend-development/S1": ["web", "MDN Web Docs", "Critical rendering path", "", null, ""],
  "frontend-development/S2": ["web", "WHATWG", "HTML Living Standard: Event loops", "", null, ""],
  "frontend-development/S3": ["web", "W3C", "Web Content Accessibility Guidelines (WCAG) 2.2", "", null, ""],
  "frontend-development/S4": ["web", "W3C", "ARIA in HTML", "", null, ""],
  "backend-services/S1": ["paper", "Internet Engineering Task Force", "HTTP Semantics", "", null, "RFC 9110"],
  "backend-services/S2": [
    "paper",
    "R. Fielding",
    "Architectural Styles and the Design of Network-based Software Architectures",
    "University of California, Irvine",
    null,
    "",
  ],
  "backend-services/S3": ["web", "A. Wiggins", "The Twelve-Factor App: Processes", "", null, ""],
  "backend-services/S4": ["web", "A. Wiggins", "The Twelve-Factor App: Port Binding", "", null, ""],
  "testing-debugging/S1": ["web", "Google Testing Blog", "Test Sizes", "", null, ""],
  "testing-debugging/S2": [
    "book",
    "Google",
    "Effective Troubleshooting",
    "Site Reliability Engineering: How Google Runs Production Systems",
    null,
    "",
  ],
  "testing-debugging/S3": ["web", "pytest", "Good Integration Practices", "pytest documentation", null, ""],
  "toolchain-automation/S1": ["book", "S. Chacon, B. Straub", "Pro Git", "", null, "Git Branching"],
  "toolchain-automation/S2": ["web", "GitHub", "Understanding GitHub Actions", "GitHub Docs", null, ""],
  "toolchain-automation/S3": ["web", "Reproducible Builds project", "Definitions: Reproducible Builds", "", null, ""],
  "maintainable-software/S1": [
    "paper",
    "D. L. Parnas",
    "On the Criteria To Be Used in Decomposing Systems into Modules",
    "Communications of the ACM",
    1972,
    "",
  ],
  "maintainable-software/S2": ["web", "M. Fowler", "Refactoring", "", null, ""],
  "maintainable-software/S3": ["web", "M. Fowler", "Technical Debt Quadrant", "", null, ""],
  "os-kernel/S1": [
    "book",
    "R. H. Arpaci-Dusseau, A. C. Arpaci-Dusseau",
    "Operating Systems: Three Easy Pieces",
    "",
    null,
    "Chapter 13, Address Spaces",
  ],
  "os-kernel/S2": ["web", "Linux Kernel Documentation", "Page Tables", "", null, ""],
  "os-kernel/S3": [
    "book",
    "R. H. Arpaci-Dusseau, A. C. Arpaci-Dusseau",
    "Operating Systems: Three Easy Pieces",
    "",
    null,
    "Files and Directories",
  ],
  "memory-hierarchy/S1": ["paper", "U. Drepper", "What Every Programmer Should Know About Memory", "", 2007, ""],
  "memory-hierarchy/S2": [
    "book",
    "R. E. Bryant, D. R. O'Hallaron",
    "Computer Systems: A Programmer's Perspective",
    "",
    null,
    "third edition",
  ],
  "memory-hierarchy/S3": "=os-kernel/S1",
  "tcp-congestion-control/S1": [
    "paper",
    "M. Allman, V. Paxson, E. Blanton",
    "TCP Congestion Control",
    "",
    2009,
    "RFC 5681",
  ],
  "tcp-congestion-control/S2": [
    "paper",
    "L. Xu, et al.",
    "CUBIC for Fast and Long-Distance Networks",
    "",
    2023,
    "RFC 9438",
  ],
  "distributed-systems/S1": [
    "web",
    "Apache Cassandra",
    "Dynamo architecture",
    "Apache Cassandra Documentation",
    null,
    "",
  ],
  "distributed-systems/S2": [
    "paper",
    "D. Ongaro, J. Ousterhout",
    "In Search of an Understandable Consensus Algorithm",
    "USENIX ATC 2014",
    2014,
    "",
  ],
  "distributed-systems/S3": [
    "web",
    "M. Featonby",
    "Making retries safe with idempotent APIs",
    "Amazon Builders' Library",
    null,
    "",
  ],
  "repeatable-deployment/S1": ["web", "Open Container Initiative", "Image Format Specification", "", null, ""],
  "repeatable-deployment/S2": ["web", "A. Wiggins", "The Twelve-Factor App: Config", "", null, ""],
  "performance-analysis/S1": ["web", "B. Gregg", "The USE Method", "", null, ""],
  "performance-analysis/S2": ["web", "B. Gregg", "Linux perf Examples", "", null, ""],
  "garbage-collection/S1": [
    "web",
    "Microsoft",
    "Fundamentals of garbage collection (.NET)",
    "Microsoft Learn",
    null,
    "",
  ],
  "garbage-collection/S2": ["web", "OpenJDK", "JEP 248: Make G1 the Default Garbage Collector", "", 2015, ""],
  "data-structures/S1": [
    "book",
    "Virginia Tech OpenDSA",
    "CS3 Data Structures and Algorithms",
    "",
    null,
    "Section 1.1",
  ],
  "data-structures/S2": [
    "web",
    "MIT OpenCourseWare",
    "Introduction to Algorithms, lecture notes",
    "",
    2020,
    "Spring 2020",
  ],
  "databases/S1": ["web", "PostgreSQL", "Introduction to MVCC", "PostgreSQL 18 Documentation", null, ""],
  "databases/S2": ["web", "PostgreSQL", "Transactions", "PostgreSQL 18 Documentation", null, ""],
  "databases/S3": ["web", "PostgreSQL", "Indexes", "PostgreSQL 18 Documentation", null, ""],
  "databases/S4": ["web", "PostgreSQL", "Reliability and the Write-Ahead Log", "PostgreSQL 18 Documentation", null, ""],
  "data-pipelines/S1": [
    "web",
    "Apache Beam",
    "Windows, watermarks, and late data",
    "Apache Beam Programming Guide",
    null,
    "",
  ],
  "data-pipelines/S2": ["web", "Apache Beam", "Basics of the Beam model", "", null, ""],
  "data-pipelines/S3": ["web", "Apache Beam", "Side Effects", "Apache Beam Programming Guide", null, ""],
  "information-retrieval/S1": [
    "book",
    "C. D. Manning, P. Raghavan, H. Schütze",
    "Introduction to Information Retrieval",
    "",
    null,
    "",
  ],
  "information-retrieval/S2": ["web", "Elastic", "Similarity settings and BM25", "Elasticsearch Reference", null, ""],
  "knowledge-management/S1": [
    "web",
    "NASA APPEL Knowledge Services",
    "Knowledge Management and Lessons Learned",
    "",
    null,
    "",
  ],
  "knowledge-management/S2": ["web", "W3C", "SKOS Simple Knowledge Organization System Reference", "", null, ""],
  "data-visualization/S1": ["book", "C. O. Wilke", "Fundamentals of Data Visualization", "", null, "Chapters 2 and 6"],
  "data-visualization/S2": [
    "web",
    "W3C",
    "Web Content Accessibility Guidelines 2.2",
    "",
    null,
    "Success Criterion 1.4.1, Use of Color",
  ],
  "algorithm-design/S1": [
    "book",
    "R. Sedgewick, K. Wayne",
    "Algorithms, 4th ed.",
    "Princeton University",
    null,
    "Section 1.4, Analysis of Algorithms",
  ],
  "algorithm-design/S2": [
    "web",
    "P. E. Black (ed.)",
    "Dictionary of Algorithms and Data Structures: Binary Search",
    "National Institute of Standards and Technology",
    null,
    "",
  ],
  "algorithm-design/S3": [
    "web",
    "R. Sedgewick, K. Wayne",
    "BinarySearch.java",
    "Algorithms, 4th ed., Princeton University",
    null,
    "Section 1.1",
  ],
  "finite-automata/S1": [
    "paper",
    "A. M. Pitts",
    "Lecture Notes on Regular Languages and Finite Automata",
    "University of Cambridge Computer Laboratory",
    2013,
    "",
  ],
  "finite-automata/S2": [
    "paper",
    "J. Gallier, J. Quaintance",
    "Introduction to the Theory of Computation: Languages, Automata and Grammars",
    "University of Pennsylvania, CIS 5110 notes",
    2026,
    "",
  ],
  "symmetry-geometry-structure/S1": ["web", "E. W. Weisstein", "Group Action", "Wolfram MathWorld", null, ""],
  "symmetry-geometry-structure/S2": ["web", "E. W. Weisstein", "Symmetry Group", "Wolfram MathWorld", null, ""],
  "compiler/S1": [
    "web",
    "Cornell University",
    "CS 4120: Compiler Introduction and Intermediate Representations",
    "",
    2026,
    "Spring 2026",
  ],
  "compiler/S2": ["web", "Cornell University", "CS 4120: Intermediate Representations", "", 2023, "Spring 2023"],
  "compiler/S3": [
    "web",
    "LLVM Project",
    "My First Language Frontend with LLVM Tutorial",
    "",
    null,
    "Chapters 2–4 and 8",
  ],
  "program-invariants/S1": [
    "book",
    "Software Foundations",
    "Programming Language Foundations",
    "University of Pennsylvania",
    null,
    "Hoare Logic, Part I",
  ],
  "program-invariants/S2": ["web", "University of Maryland", "CMSC 433, Notes 9: Loop Invariants", "", 2025, ""],
  "l-system/S1": [
    "book",
    "P. Prusinkiewicz, A. Lindenmayer",
    "The Algorithmic Beauty of Plants",
    "Springer-Verlag",
    1990,
    "electronic edition 2004",
  ],
  "l-system/S2": [
    "paper",
    "P. Prusinkiewicz, M. Hammel, J. Hanan, R. Měch",
    "L-systems: from the theory to visual models of plants",
    "Proceedings of the 2nd CSIRO Symposium on Computational Challenges in Life Sciences",
    1996,
    "",
  ],
  "authentication-authorization/S1": [
    "web",
    "OWASP",
    "Authentication Cheat Sheet",
    "OWASP Cheat Sheet Series",
    null,
    "",
  ],
  "authentication-authorization/S2": [
    "web",
    "OWASP",
    "Authorization Cheat Sheet",
    "OWASP Cheat Sheet Series",
    null,
    "",
  ],
  "encryption-hashing-signatures/S1": [
    "paper",
    "National Institute of Standards and Technology",
    "Secure Hash Standard (SHS)",
    "",
    null,
    "FIPS PUB 180-4",
  ],
  "encryption-hashing-signatures/S2": [
    "paper",
    "National Institute of Standards and Technology",
    "Digital Signature Standard (DSS)",
    "",
    null,
    "FIPS PUB 186-5",
  ],
  "encryption-hashing-signatures/S3": [
    "web",
    "OWASP",
    "Cryptographic Storage Cheat Sheet",
    "OWASP Cheat Sheet Series",
    null,
    "",
  ],
  "data-minimization/S1": [
    "archive",
    "Regulation (EU) 2016/679",
    "Article 5: Principles relating to processing of personal data",
    "UK-retained version",
    null,
    "",
  ],
  "data-minimization/S2": [
    "archive",
    "Regulation (EU) 2016/679",
    "Article 25: Data protection by design and by default",
    "UK-retained version",
    null,
    "",
  ],
  "failure-redundancy-recovery/S1": [
    "book",
    "R. Ewaschuk",
    "Monitoring Distributed Systems",
    "Site Reliability Engineering: How Google Runs Production Systems",
    null,
    "",
  ],
  "failure-redundancy-recovery/S2": [
    "web",
    "Amazon Web Services",
    "Reliability Pillar",
    "AWS Well-Architected Framework",
    null,
    "",
  ],
  "logs-metrics-traces/S1": ["web", "OpenTelemetry Authors", "Signals", "OpenTelemetry Concepts", null, ""],
  "logs-metrics-traces/S2": "=failure-redundancy-recovery/S1",
  "threat-modeling/S1": ["web", "OWASP", "Threat Modeling Cheat Sheet", "OWASP Cheat Sheet Series", null, ""],
  "threat-modeling/S2": ["web", "Microsoft", "Microsoft Threat Modeling Tool overview", "Microsoft Learn", null, ""],
  "effective-learning/S1": [
    "paper",
    "J. Dunlosky, K. A. Rawson, E. J. Marsh, M. J. Nathan, D. T. Willingham",
    "Improving Students' Learning With Effective Learning Techniques: Promising Directions From Cognitive and Educational Psychology",
    "Psychological Science in the Public Interest 14(1), 4–58",
    2013,
    "doi:10.1177/1529100612453266",
  ],
  "effective-learning/S2": [
    "paper",
    "N. J. Cepeda, H. Pashler, E. Vul, J. T. Wixted, D. Rohrer",
    "Distributed Practice in Verbal Recall Tasks: A Review and Quantitative Synthesis",
    "Psychological Bulletin 132(3), 354–380",
    2006,
    "doi:10.1037/0033-2909.132.3.354",
  ],
  "effective-learning/S3": [
    "paper",
    "J. D. Karpicke, J. R. Blunt",
    "Retrieval Practice Produces More Learning than Elaborative Studying with Concept Mapping",
    "Science 331(6018), 772–775",
    2011,
    "doi:10.1126/science.1199327",
  ],
  "technical-documentation/S1": [
    "web",
    "Diátaxis",
    "Documentation System: Tutorials, How-to Guides, Reference, and Explanation",
    "",
    null,
    "",
  ],
  "technical-documentation/S2": ["web", "Google", "Google Developer Documentation Style Guide", "", null, ""],
  "notes-to-knowledge/S1": "=effective-learning/S1",
  "notes-to-knowledge/S2": "=effective-learning/S2",
  "collaborative-work/S1": [
    "paper",
    "E. Salas, D. E. Sims, C. S. Burke",
    "Is There a “Big Five” in Teamwork?",
    "Small Group Research 36(5), 555–599",
    2005,
    "doi:10.1177/1046496405277134",
  ],
  "collaborative-work/S2": [
    "paper",
    "A. Edmondson",
    "Psychological Safety and Learning Behavior in Work Teams",
    "Administrative Science Quarterly 44(2), 350–383",
    1999,
    "doi:10.2307/2666999",
  ],
  "effective-code-review/S1": [
    "web",
    "Google",
    "What to Look for in a Code Review",
    "Engineering Practices Documentation",
    null,
    "",
  ],
  "effective-code-review/S2": [
    "web",
    "Google",
    "The Standard of Code Review",
    "Engineering Practices Documentation",
    null,
    "",
  ],
  "technical-discussion/S1": [
    "paper",
    "M. K. Smith, W. B. Wood, W. K. Adams, C. Wieman, J. K. Knight, N. Guild, T. T. Su",
    "Why Peer Discussion Improves Student Performance on In-Class Concept Questions",
    "Science 323(5910), 122–124",
    2009,
    "doi:10.1126/science.1165919",
  ],
  "technical-discussion/S2": "=collaborative-work/S2",
  "parser/parser-llvm": ["web", "LLVM Project", "Kaleidoscope: Implementing a Parser and AST", "", null, ""],
  "parser/parser-nystrom": ["book", "R. Nystrom", "Crafting Interpreters", "", null, "Parsing Expressions"],
  "ant-colony-optimization/S1": [
    "paper",
    "M. Dorigo",
    "Ant colony optimization",
    "Scholarpedia 2(3):1461",
    2007,
    "doi:10.4249/scholarpedia.1461",
  ],
  "ant-colony-optimization/S2": [
    "web",
    "IRIDIA, Université libre de Bruxelles",
    "Ant Colony Optimization: Public Software",
    "",
    null,
    "",
  ],
  "b-tree/S1": [
    "book",
    "Virginia Tech OpenDSA",
    "CS3 Data Structures and Algorithms",
    "",
    null,
    "Section 12.6, B-Trees",
  ],
  "b-tree/S2": ["web", "SQLite", "Database File Format: B-tree Pages", "SQLite Documentation", null, ""],
  "bloom-filter/S1": ["web", "Google Guava", "BloomFilter API and implementation", "", null, ""],
  "bloom-filter/S2": ["web", "Redis", "Bloom filter data type", "Redis Documentation", null, ""],
  "cache-line/S1": ["web", "Linux Kernel Documentation", "False Sharing", "", null, ""],
  "cache-line/S2": ["web", "Intel", "Intel 64 and IA-32 Architectures Software Developer Manuals", "", null, ""],
  "gossip-protocol/S1": ["web", "HashiCorp", "Gossip", "Consul Documentation", null, ""],
  "gossip-protocol/S2": "=distributed-systems/S1",
  "paxos/S1": ["paper", "L. Lamport", "Paxos Made Simple", "", 2001, ""],
  "paxos/S2": [
    "paper",
    "T. D. Chandra, R. Griesemer, J. Redstone",
    "Paxos Made Live: An Engineering Perspective",
    "",
    2007,
    "",
  ],
  "raft-consensus/S1": "=distributed-systems/S2",
  "raft-consensus/S2": ["web", "Raft Project", "The Raft Consensus Algorithm", "", null, ""],
};
